# Generated by Django 6.0.3 on 2026-03-13 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(choices=[('merge_pdf', 'Merge PDFs'), ('compress_pdf', 'Compress PDF'), ('split_pdf', 'Split PDF'), ('pdf_to_images', 'PDF to Images'), ('docx_to_pdf', 'DOCX to PDF'), ('txt_to_pdf', 'TXT to PDF'), ('img_to_pdf', 'Image to PDF'), ('jpg_to_png', 'JPG to PNG'), ('png_to_jpg', 'PNG to JPG'), ('resize_image', 'Resize Image')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('input_size', models.BigIntegerField(default=0)),
                ('output_size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
