# Generated by Django 6.0.3 on 2026-03-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='tool',
            field=models.CharField(choices=[('merge_pdf', 'Merge PDFs'), ('compress_pdf', 'Compress PDF'), ('split_pdf', 'Split PDF'), ('pdf_to_images', 'PDF to Images'), ('docx_to_pdf', 'DOCX to PDF'), ('txt_to_pdf', 'TXT to PDF'), ('img_to_pdf', 'Image to PDF'), ('jpg_to_png', 'JPG to PNG'), ('png_to_jpg', 'PNG to JPG'), ('resize_image', 'Resize Image'), ('pdf_to_word', 'PDF to Word'), ('any_to_pdf', 'Any to PDF')], max_length=50),
        ),
    ]
