# Generated by Django 4.2.29 on 2026-03-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0003_conversionjob_is_guest_conversionjob_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionjob",
            name="tool",
            field=models.CharField(
                choices=[
                    ("merge_pdf", "Merge PDFs"),
                    ("compress_pdf", "Compress PDF"),
                    ("split_pdf", "Split PDF"),
                    ("pdf_to_images", "PDF to Images"),
                    ("docx_to_pdf", "DOCX to PDF"),
                    ("txt_to_pdf", "TXT to PDF"),
                    ("img_to_pdf", "Image to PDF"),
                    ("jpg_to_png", "JPG to PNG"),
                    ("png_to_jpg", "PNG to JPG"),
                    ("resize_image", "Resize Image"),
                    ("pdf_to_word", "PDF to Word"),
                    ("any_to_pdf", "Any to PDF"),
                    ("password_protect", "Password Protect PDF"),
                    ("unlock_pdf", "Unlock PDF"),
                    ("rotate_pdf", "Rotate PDF"),
                    ("watermark_pdf", "Watermark PDF"),
                    ("add_page_numbers", "Add Page Numbers"),
                    ("pdf_to_excel", "PDF to Excel"),
                    ("excel_to_pdf", "Excel to PDF"),
                    ("pptx_to_pdf", "PowerPoint to PDF"),
                    ("pdf_to_pptx", "PDF to PowerPoint"),
                    ("html_to_pdf", "HTML to PDF"),
                    ("ocr_pdf", "OCR Searchable PDF"),
                    ("extract_text", "Extract Text"),
                    ("extract_images", "Extract Images"),
                ],
                max_length=50,
            ),
        ),
    ]
