# Generated by Django 4.2.29 on 2026-03-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0004_alter_conversionjob_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
