# Generated by Django 4.2.30 on 2026-06-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_alter_conversionjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='converter_g_ip_addr_f1b817_idx')],
            },
        ),
    ]
