# Generated by Django 4.2.30 on 2026-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_guestusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
