# Generated by Django 4.2.29 on 2026-03-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("webhook_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Developer", "Developer"),
                            ("Pro", "Pro"),
                        ],
                        default="Free",
                        max_length=20,
                    ),
                ),
                ("api_calls_used_this_month", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
