# Generated by Django 4.2.29 on 2026-03-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="plan_tier",
            field=models.CharField(
                choices=[
                    ("Free", "Free"),
                    ("Developer", "Developer"),
                    ("Corporate", "Corporate"),
                ],
                default="Free",
                max_length=20,
            ),
        ),
    ]
