# Generated by Django 4.2.29 on 2026-03-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_profile_plan_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
