# Generated by Django 4.2.29 on 2026-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_profile_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plan_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="plan_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
