# Generated by Django 4.2.30 on 2026-06-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_plan_expiry_date_profile_plan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
