# Generated by Django 4.2.30 on 2026-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_razorpay_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_quota_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
