# Generated by Django 6.0.3 on 2026-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationjob",
            name="source_lang",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect"),
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="translationjob",
            name="target_lang",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect"),
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
